# Generated by Django 5.1.1 on 2024-09-29 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="logos", verbose_name="Product image"
            ),
        ),
    ]
